### ISSUE TITLE
0 Results

### ISSUE THREAD

**Issue by Alfagun74** [Akif9748/async-g-i-s#1]
I get 0 Results sometimes. 

What could be the cause of it?
Is there a rate limit?

**Comment by Akif9748** [comment]
Can you show your `arguments` you give to the gis function?
I didn't encounter any rate limits but maybe...
But i think main reason is query. Example, safe=on query can eliminates all results.

**Comment by Alfagun74** [comment]
i call it like this:
``await gis("Inscryption 2021 cover box art");``

**Comment by Akif9748** [comment]
Hmm, i did not see a problem. 
And i think it is not ratelimit:
```js
    setInterval(async () => {
      const results = await gis("Inscryption 2021 cover box art");
      console.log(results.slice(0, 10));
      console.timeEnd();
    }, 100)
```
This code is working perfectly.
```js
[
  {
    url: 'https://www.mobygames.com/images/covers/l/771534-inscryption-linux-front-cover.jpg',
    height: 370,
    width: 800
  },
  {
    url: 'https://m.media-amazon.com/images/M/MV5BMjE0YzI5NGItMmQ4MC00YTU4LTgxYmItNmQ3YjQ5MjY0MjZmXkEyXkFqcGdeQXVyMTA0MTM5NjI2._V1_FMjpg_UX1000_.jpg',
    height: 1500,
    width: 1000
  },
  {
    url: 'https://upload.wikimedia.org/wikipedia/en/4/48/Inscryption_Cover_Art.jpg',
    height: 237,
    width: 421
  },
  {
    url: 'https://gamefaqs.gamespot.com/a/box/1/1/4/829114_front.jpg',
    height: 853,
    width: 640
  },
  {
    url: 'https://i.etsystatic.com/28129798/r/il/e8e43e/4121816562/il_570xN.4121816562_5t1c.jpg',
    height: 382,
    width: 570
  },
  {
    url: 'https://assets2.rockpapershotgun.com/inscryption-screen5.jpg/BROK/thumbnail/1200x1200/quality/100/inscryption-screen5.jpg',
    height: 1200,
    width: 1200
  },
  {
    url: 'https://cdn.vox-cdn.com/thumbor/65AZeRBYUw5Ndksgc4R2b1dcPVw\\u003d/0x0:1920x1079/1200x0/filters:focal(0x0:1920x1079):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/23289514/ss_0191a69b0e94a9a7784f5b81e27f06379910645a.jpeg',
    height: 674,
    width: 1200
  },
  {
    url: 'https://sm.ign.com/ign_in/gallery/i/inscryptio/inscryption-gameplay-screenshots_xq75.jpg',
    height: 1079,
    width: 1920
  },
  {
    url: 'https://ih1.redbubble.net/image.3533916456.0090/fposter,small,wall_texture,product,750x1000.jpg',
    height: 1000,
    width: 750
  },
  {
    url: 'https://progameguides.com/wp-content/uploads/2021/10/Featured-Inscryption-All-items-in-Inscryption.jpg',
    height: 675,
    width: 1200
  }
]
```
And returns values. 
https://www.google.com/search?tbm=isch&q=Inscryption%202021%20cover%20box%20art
Is that link working on you?
I cant found problem...

**Comment by Alfagun74** [comment]
Try putting it in a while loop with a counter and test the limit please

**Comment by Akif9748** [comment]
No problem:
![image](https://user-images.githubusercontent.com/70021050/188975247-663f7d6d-0281-41cd-a1f8-7f3f405257ff.png)

**Comment by Alfagun74** [comment]
How long did you run it? My problems started occuring between 300 and 600 requests.

**Comment by Alfagun74** [comment]
i suppose its a rata limit by google

**Comment by Alfagun74** [comment]
btw thank you so much for this library! Maybe you are interested in how we use it: https://github.com/Phalcode/crackpipe-backend/blob/2c47a86c44f267f9539dde1c990c17a42a5ad62a/src/services/box-art.service.ts#L108

**Comment by Akif9748** [comment]
I closed it due last update, no ratelimit based but module based errors fixed.
Thanks you too using this module. Sure i interested. Because i am looking all repos used my module. But %99 of them was same project's forks.
I love how you used ts definations:
![image](https://github.com/Akif9748/async-g-i-s/assets/70021050/7bafe8ea-86d0-439c-850b-b393a9847c62)
I've never seen anyone use.
And, i will do this module zero-depenecies.

**Comment by Alfagun74** [comment]
Aslansin Kardeșim ❤️

**Comment by Akif9748** [comment]
65531a8 ile direkt 0 modülle çalışır hale getirdim. Biraz daha hızlı.
